//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_averagers_Model_Trigger;
        
        private static SteamVR_Action_Boolean p_averagers_Model_Grip;
        
        private static SteamVR_Action_Boolean p_averagers_Model_Button_1;
        
        private static SteamVR_Action_Boolean p_averagers_Model_Touchpad_Button;
        
        private static SteamVR_Action_Boolean p_averagers_Model_Touchpad_Touch;
        
        private static SteamVR_Action_Vector2 p_averagers_Model_Touchpad_Position;
        
        private static SteamVR_Action_Pose p_averagers_Model_Pose;
        
        private static SteamVR_Action_Vibration p_averagers_Model_Haptic;
        
        public static SteamVR_Action_Boolean averagers_Model_Trigger
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Trigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean averagers_Model_Grip
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean averagers_Model_Button_1
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Button_1.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean averagers_Model_Touchpad_Button
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Touchpad_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean averagers_Model_Touchpad_Touch
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Touchpad_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 averagers_Model_Touchpad_Position
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Touchpad_Position.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose averagers_Model_Pose
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration averagers_Model_Haptic
        {
            get
            {
                return SteamVR_Actions.p_averagers_Model_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.averagers_Model_Trigger,
                    SteamVR_Actions.averagers_Model_Grip,
                    SteamVR_Actions.averagers_Model_Button_1,
                    SteamVR_Actions.averagers_Model_Touchpad_Button,
                    SteamVR_Actions.averagers_Model_Touchpad_Touch,
                    SteamVR_Actions.averagers_Model_Touchpad_Position,
                    SteamVR_Actions.averagers_Model_Pose,
                    SteamVR_Actions.averagers_Model_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.averagers_Model_Trigger,
                    SteamVR_Actions.averagers_Model_Grip,
                    SteamVR_Actions.averagers_Model_Button_1,
                    SteamVR_Actions.averagers_Model_Touchpad_Button,
                    SteamVR_Actions.averagers_Model_Touchpad_Touch,
                    SteamVR_Actions.averagers_Model_Touchpad_Position,
                    SteamVR_Actions.averagers_Model_Pose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.averagers_Model_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.averagers_Model_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.averagers_Model_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.averagers_Model_Trigger,
                    SteamVR_Actions.averagers_Model_Grip,
                    SteamVR_Actions.averagers_Model_Button_1,
                    SteamVR_Actions.averagers_Model_Touchpad_Button,
                    SteamVR_Actions.averagers_Model_Touchpad_Touch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.averagers_Model_Touchpad_Position};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.averagers_Model_Trigger,
                    SteamVR_Actions.averagers_Model_Grip,
                    SteamVR_Actions.averagers_Model_Button_1,
                    SteamVR_Actions.averagers_Model_Touchpad_Button,
                    SteamVR_Actions.averagers_Model_Touchpad_Touch,
                    SteamVR_Actions.averagers_Model_Touchpad_Position};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_averagers_Model_Trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Averagers_Model/in/Trigger")));
            SteamVR_Actions.p_averagers_Model_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Averagers_Model/in/Grip")));
            SteamVR_Actions.p_averagers_Model_Button_1 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Averagers_Model/in/Button_1")));
            SteamVR_Actions.p_averagers_Model_Touchpad_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Averagers_Model/in/Touchpad_Button")));
            SteamVR_Actions.p_averagers_Model_Touchpad_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Averagers_Model/in/Touchpad_Touch")));
            SteamVR_Actions.p_averagers_Model_Touchpad_Position = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Averagers_Model/in/Touchpad_Position")));
            SteamVR_Actions.p_averagers_Model_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Averagers_Model/in/Pose")));
            SteamVR_Actions.p_averagers_Model_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Averagers_Model/out/Haptic")));
        }
    }
}
