//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Averagers_Model : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button_1
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Button_1;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad_Button
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Touchpad_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad_Touch
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Touchpad_Touch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad_Position
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Touchpad_Position;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.averagers_Model_Haptic;
            }
        }
    }
}
